-- MySQL Script generated by MySQL Workbench
-- Sat Sep 27 18:12:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema makibase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema makibase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `makibase` DEFAULT CHARACTER SET utf8 ;
USE `makibase` ;

-- -----------------------------------------------------
-- Table `makibase`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `descripcion` VARCHAR(65) NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `estado` ENUM('activo', 'inactivo') NOT NULL DEFAULT 'activo',
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_Usuario_Rol1_idx` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `makibase`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Permiso` (
  `idPermiso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(65) NULL,
  PRIMARY KEY (`idPermiso`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Permiso_Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Permiso_Rol` (
  `Rol_idRol` INT NOT NULL,
  `Permiso_idPermiso` INT NOT NULL,
  PRIMARY KEY (`Rol_idRol`, `Permiso_idPermiso`),
  INDEX `fk_Permiso_Rol_Permiso1_idx` (`Permiso_idPermiso` ASC) VISIBLE,
  CONSTRAINT `fk_Permiso_Rol_Rol`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `makibase`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Permiso_Rol_Permiso1`
    FOREIGN KEY (`Permiso_idPermiso`)
    REFERENCES `makibase`.`Permiso` (`idPermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `descripcion` VARCHAR(65) NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`UnidadMedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`UnidadMedida` (
  `idUnidadMedida` INT NOT NULL AUTO_INCREMENT,
  `medida` VARCHAR(45) NOT NULL,
  `abreviatura` VARCHAR(10) NOT NULL,
  `medidaEquivalente` VARCHAR(45) NULL,
  `factorConversion` DECIMAL(10,3) NULL,
  PRIMARY KEY (`idUnidadMedida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `estado` ENUM('vigente', 'descontinuado', 'suspendido') NOT NULL DEFAULT 'vigente',
  `Categoria_idCategoria` INT NOT NULL,
  `UnidadMedida_idUnidadMedida` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_Producto_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Producto_UnidadMedida1_idx` (`UnidadMedida_idUnidadMedida` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `makibase`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_UnidadMedida1`
    FOREIGN KEY (`UnidadMedida_idUnidadMedida`)
    REFERENCES `makibase`.`UnidadMedida` (`idUnidadMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NOT NULL,
  `estado` ENUM('activo', 'inactivo') NOT NULL DEFAULT 'activo',
  PRIMARY KEY (`idProveedor`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`InventarioProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`InventarioProducto` (
  `idInventarioProducto` INT NOT NULL AUTO_INCREMENT,
  `Producto_idProducto` INT NOT NULL,
  `cantidadMaxima` INT NOT NULL,
  `cantidadMinima` INT NOT NULL,
  `cantidadActual` DECIMAL(10,3) NOT NULL,
  `fechaCaducidad` DATETIME NOT NULL,
  `fechaIngreso` DATETIME NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `UnidadMedida_idUnidadMedida` INT NOT NULL,
  PRIMARY KEY (`idInventarioProducto`),
  INDEX `fk_InventarioProducto_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_InventarioProducto_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  INDEX `fk_InventarioProducto_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_InventarioProducto_UnidadMedida1_idx` (`UnidadMedida_idUnidadMedida` ASC) VISIBLE,
  CONSTRAINT `fk_InventarioProducto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `makibase`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InventarioProducto_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `makibase`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InventarioProducto_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `makibase`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InventarioProducto_UnidadMedida1`
    FOREIGN KEY (`UnidadMedida_idUnidadMedida`)
    REFERENCES `makibase`.`UnidadMedida` (`idUnidadMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `estado` ENUM('entregado', 'pendiente', 'cancelado') NOT NULL DEFAULT 'pendiente',
  `Usuario_idUsuario` INT NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Pedido_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `makibase`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `makibase`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Producto_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Producto_Pedido` (
  `idProducto_Pedido` INT NOT NULL AUTO_INCREMENT,
  `Producto_idProducto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `cantidad` DECIMAL(10,3) NOT NULL,
  `UnidadMedida_idUnidadMedida` INT NOT NULL,
  PRIMARY KEY (`idProducto_Pedido`),
  INDEX `fk_Producto_Pedido_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_Producto_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Producto_Pedido_UnidadMedida1_idx` (`UnidadMedida_idUnidadMedida` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Pedido_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `makibase`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `makibase`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Pedido_UnidadMedida1`
    FOREIGN KEY (`UnidadMedida_idUnidadMedida`)
    REFERENCES `makibase`.`UnidadMedida` (`idUnidadMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Mesa` (
  `idMesa` INT NOT NULL AUTO_INCREMENT,
  `estado` ENUM('disponible', 'ocupada', 'inhabilitada') NOT NULL DEFAULT 'disponible',
  `numeroMesa` INT NOT NULL,
  PRIMARY KEY (`idMesa`),
  UNIQUE INDEX `numeroMesa_UNIQUE` (`numeroMesa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Orden` (
  `idOrden` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT NOT NULL,
  `Mesa_idMesa` INT NOT NULL,
  `estado` ENUM('cerrada', 'abierta') NOT NULL DEFAULT 'abierta',
  `total` DECIMAL(10,2) NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`idOrden`),
  INDEX `fk_Orden_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Orden_Mesa1_idx` (`Mesa_idMesa` ASC) VISIBLE,
  CONSTRAINT `fk_Orden_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `makibase`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orden_Mesa1`
    FOREIGN KEY (`Mesa_idMesa`)
    REFERENCES `makibase`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Platillo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Platillo` (
  `idPlatillo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `descripcion` VARCHAR(65) NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `estado` ENUM('disponible', 'agotado', 'descontinuado') NOT NULL DEFAULT 'disponible',
  PRIMARY KEY (`idPlatillo`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Platillo_Orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Platillo_Orden` (
  `Orden_idOrden` INT NOT NULL,
  `Platillo_idPlatillo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` ENUM('pendiente', 'entregado', 'preparacion', 'cancelado') NOT NULL DEFAULT 'pendiente',
  `precioUnitario` DECIMAL(10,2) NOT NULL,
  INDEX `fk_Platillo_Orden_Orden1_idx` (`Orden_idOrden` ASC) VISIBLE,
  INDEX `fk_Platillo_Orden_Platillo1_idx` (`Platillo_idPlatillo` ASC) VISIBLE,
  PRIMARY KEY (`Orden_idOrden`, `Platillo_idPlatillo`),
  CONSTRAINT `fk_Platillo_Orden_Orden1`
    FOREIGN KEY (`Orden_idOrden`)
    REFERENCES `makibase`.`Orden` (`idOrden`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Platillo_Orden_Platillo1`
    FOREIGN KEY (`Platillo_idPlatillo`)
    REFERENCES `makibase`.`Platillo` (`idPlatillo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Producto_Platillo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Producto_Platillo` (
  `Platillo_idPlatillo` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `UnidadMedida_idUnidadMedida` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`Platillo_idPlatillo`, `Producto_idProducto`),
  INDEX `fk_Producto_Platillo_UnidadMedida1_idx` (`UnidadMedida_idUnidadMedida` ASC) VISIBLE,
  INDEX `fk_Producto_Platillo_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Platillo_Platillo1`
    FOREIGN KEY (`Platillo_idPlatillo`)
    REFERENCES `makibase`.`Platillo` (`idPlatillo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Platillo_UnidadMedida1`
    FOREIGN KEY (`UnidadMedida_idUnidadMedida`)
    REFERENCES `makibase`.`UnidadMedida` (`idUnidadMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Platillo_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `makibase`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makibase`.`Imprevisto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makibase`.`Imprevisto` (
  `idImprevisto` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuarioReporta` INT NOT NULL,
  `InventarioProducto_idInventarioProducto` INT NOT NULL,
  `descripcion` VARCHAR(75) NULL,
  `fecha` DATETIME NOT NULL,
  `cantidad` INT NOT NULL,
  `UnidadMedida_idUnidadMedida` INT NOT NULL,
  `estado` ENUM('autorizado', 'pendiente', 'rechazado') NOT NULL,
  `Usuario_idUsuarioAutoriza` INT NULL,
  PRIMARY KEY (`idImprevisto`),
  INDEX `fk_Imprevisto_Usuario1_idx` (`Usuario_idUsuarioReporta` ASC) VISIBLE,
  INDEX `fk_Imprevisto_InventarioProducto1_idx` (`InventarioProducto_idInventarioProducto` ASC) VISIBLE,
  INDEX `fk_Imprevisto_UnidadMedida1_idx` (`UnidadMedida_idUnidadMedida` ASC) VISIBLE,
  INDEX `fk_Imprevisto_Usuario2_idx` (`Usuario_idUsuarioAutoriza` ASC) VISIBLE,
  CONSTRAINT `fk_Imprevisto_Usuario1`
    FOREIGN KEY (`Usuario_idUsuarioReporta`)
    REFERENCES `makibase`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imprevisto_InventarioProducto1`
    FOREIGN KEY (`InventarioProducto_idInventarioProducto`)
    REFERENCES `makibase`.`InventarioProducto` (`idInventarioProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imprevisto_UnidadMedida1`
    FOREIGN KEY (`UnidadMedida_idUnidadMedida`)
    REFERENCES `makibase`.`UnidadMedida` (`idUnidadMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imprevisto_Usuario2`
    FOREIGN KEY (`Usuario_idUsuarioAutoriza`)
    REFERENCES `makibase`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
